### PR TITLE
Large swath of updates

### PR DESCRIPTION
**Pull request by warmwaffles**
Since this gem was stagnant and we are using it in our application.

I went through updated the following:
- Tests were refactored and made to be more concise.
- Gemspec file to follow a more modern approach.
- Moved the parser to be a class within a set of modules.
- Readme needed some updating to make things a little clearer.
- Added tests to run against a large set of ruby versions to ensure compatibility.

If you no longer wish to maintain this gem, I'd be more than happy to take over.

### CODE REVIEW

**Comment by jhubert** [comment]
@ingydotnet Any chance this'll get merged in?

**Comment by jhubert** [comment]
@warmwaffles Any interest in taking this over in a new repo? Seems like this one may be dead.

**Comment by warmwaffles** [comment]
I actually don't have any interest in this anymore.

**Comment by ingydotnet** [comment]
Hi. I certainly have no interest in this anymore. But I merged and pushed the changes anyway. Enjoy...

**Comment by jhubert** [comment]
Thank you!

**Pull request merged**
